apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-app-config
  namespace: laravel-app
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  APP_KEY: "base64:vg6axnRyopHecNpxuoDTXIbZDFG9RXUeHpHZw7t/DSE="
  APP_TIMEZONE: "UTC"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"
  BCRYPT_ROUNDS: "12"
  
  LOG_CHANNEL: "stdout"
  LOG_LEVEL: "debug"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "sail"
  DB_PASSWORD: "password"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DRIVER: "local"
  QUEUE_CONNECTION: "redis"
  
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  MEMCACHED_HOST: "memcached"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Laravel"
  
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  
  PUSHER_APP_ID: ""
  PUSHER_APP_CLUSTER: "mt1"
  MIX_PUSHER_APP_KEY: ""
  
  VITE_APP_NAME: "Laravel"

  LOG_STDOUT_FORMATTER: "stdout"