apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
  namespace: laravel-app
type: Opaque
stringData:
  APP_KEY: "base64:vg6axnRyopHecNpxuoDTXIbZDFG9RXUeHpHZw7t/DSE="
  DB_USERNAME: "sail"
  DB_PASSWORD: "password"
  REDIS_PASSWORD: "null"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"