apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    tier: backend
    layer: webserver
  namespace: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: webserver
  template:
    metadata:
      labels:
        tier: backend
        layer: webserver
    spec:
      containers:
        - name: webserver
          image: yamahn/web_server:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: laravel-app-config
          env:
            - name: FPM_HOST
              value: 'fpm:9000'
          volumeMounts:
            - mountPath: /var/www/html
              name: laravel-storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-pvc