apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: laravel-app
spec:
  type: LoadBalancer
  selector:
    tier: backend
    layer: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80