apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: laravel-app
spec:
  selector:
    tier: backend
    layer: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306