apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm
  labels:
    tier: backend
    layer: fpm
  namespace: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: yamahn/cli:latest
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: laravel-app-config
            - secretRef:
                name: laravel-app-secret
      containers:
        - name: fpm
          image: yamahn/fpm:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-app-config
            - secretRef:
                name: laravel-app-secret
          volumeMounts:
            - mountPath: /var/www/html
              name: laravel-storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-pvc